unit G2OpenALTypes;
{$include Gen2MP.inc}
interface

type
  TALBoolean = Boolean;
  PALBoolean = ^TALBoolean;
  TALByte = ShortInt;
  PALByte = ^TALByte;
  TALUByte = Byte;
  PALUByte = ^TALUByte;
  TALShort = SmallInt;
  PALShort = ^TALShort;
  TALUShort = Word;
  PALUShort = ^TALUShort;
  TALUInt = LongWord;
  PALUInt = ^TALUInt;
  TALInt = Integer;
  PALInt = ^TALInt;
  TALFloat = Single;
  PALFloat = ^TALFloat;
  TALDouble = Double;
  PALDouble = ^TALDouble;
  TALSizei = LongWord;
  PALSizei = ^TALSizei;
  TALVoid = Pointer;
  PALVoid = ^TALVoid;
  PPALVoid = ^PALVoid;
  TALEnum = Integer;
  PALEnum = ^TALEnum;
  TALBitField = LongWord;
  PALBitField = ^TALBitField;
  TALClampf = TALFloat;
  PALClampf = ^TALClampf;
  TALClampd = TALDouble;
  PALClampd = ^TALClampd;
  TALCBoolean = Boolean;
  PALCBoolean = ^TALCBoolean;
  TALCByte = ShortInt;
  PALCByte = ^TALCByte;
  TALCUByte = Byte;
  PALCUByte = ^TALCUByte;
  TALCShort = SmallInt;
  PALCShort = ^TALCShort;
  TALCUShort = Word;
  PALCUShort = ^TALCUShort;
  TALCUInt = LongWord;
  PALCUInt = ^TALCUInt;
  TALCInt = Integer;
  PALCInt = ^TALCInt;
  TALCFloat = Single;
  PALCFloat = ^TALCFloat;
  TALCDouble = Double;
  PALCDouble = ^TALCDouble;
  TALCSizei = Integer;
  PALCSizei = ^TALCSizei;
  TALCEnum = Integer;
  PALCEnum = ^TALCEnum;
  TALCVoid = Pointer;
  PALCVoid = ^TALCvoid;
  PALCContext = ^TALCContext;
  TALCContext = TALCVoid;
  PALCDevice = ^TALCDevice;
  TALCDevice = TALCVoid;

const
  AL_INVALID = -1;
  AL_NONE = 0;
  AL_FALSE = 0;
  AL_TRUE = 1;

  AL_SOURCE_TYPE = $200;
  AL_SOURCE_ABSOLUTE = $201;
  AL_SOURCE_RELATIVE = $202;
  AL_SOURCE_MULTICHANNEL = $204;
  AL_SOURCE_POINT = $205;

  AL_CONE_INNER_ANGLE = $1001;
  AL_CONE_OUTER_ANGLE = $1002;
  AL_PITCH = $1003;
  AL_POSITION = $1004;
  AL_DIRECTION = $1005;
  AL_VELOCITY = $1006;
  AL_LOOPING = $1007;
  AL_STREAMING = $1008;
  AL_BUFFER = $1009;
  AL_GAIN = $100A;
  AL_SOURCE_AMBIENT = $100B;
  AL_BYTE_LOKI = $100C;
  AL_MIN_GAIN = $100D;
  AL_MAX_GAIN = $100E;
  AL_ORIENTATION = $100F;
  AL_SOURCE_STATE = $1010;
  AL_INITIAL = $1011;
  AL_PLAYING = $1012;
  AL_PAUSED = $1013;
  AL_STOPPED = $1014;
  AL_BUFFERS_QUEUED = $1015;
  AL_BUFFERS_PROCESSED = $1016;

  AL_FORMAT_MONO8 = $1100;
  AL_FORMAT_MONO16 = $1101;
  AL_FORMAT_STEREO8 = $1102;
  AL_FORMAT_STEREO16 = $1103;

  AL_REFERENCE_DISTANCE = $1020;
  AL_ROLLOFF_FACTOR = $1021;
  AL_CONE_OUTER_GAIN = $1022;
  AL_MAX_DISTANCE = $1023;

  AL_FREQUENCY = $2001;
  AL_BITS = $2002;
  AL_CHANNELS = $2003;
  AL_SIZE = $2004;
  AL_DATA = $2005;

  AL_UNUSED = $2010;
  AL_PENDING = $2011;
  AL_CURRENT = $2012;

  AL_NO_ERROR = AL_FALSE;
  AL_INVALID_NAME = $A001;
  AL_INVALID_ENUM = $A002;
  AL_INVALID_VALUE = $A003;
  AL_INVALID_OPERATION = $A004;
  AL_OUT_OF_MEMORY = $A005;

  AL_VENDOR = $B001;
  AL_VERSION = $B002;
  AL_RENDERER = $B003;
  AL_EXTENSIONS = $B004;

  AL_DOPPLER_FACTOR = $C000;
  AL_DOPPLER_VELOCITY = $C001;
  AL_DISTANCE_SCALE = $C002;

  AL_DISTANCE_MODEL = $D000;
  AL_INVERSE_DISTANCE = $D001;
  AL_INVERSE_DISTANCE_CLAMPED = $D002;

  AL_CHANNEL_MASK = $3000;
  AL_ENV_ROOM_IASIG = $3001;
  AL_ENV_ROOM_HIGH_FREQUENCY_IASIG = $3002;
  AL_ENY_ROOM_ROLLOFF_FACTOR_IASIG = $3003;
  AL_ENV_DECAY_TIME_IASIG = $3004;
  AL_ENV_DECAY_HIGH_FREQUENCY_RATIO_IASIG = $3005;
  AL_ENV_REFLECTIONS_IASIG = $3006;
  AL_ENV_REFLECTIONS_DELAY_IASIG = $3006;
  AL_ENV_REVERB_IASIG = $3007;
  AL_ENV_REVERB_DELAY_IASIG = $3008;
  AL_ENV_DIFFUSION_IASIG = $3009;
  AL_ENV_DENSITY_IASIG = $300A;
  AL_ENV_HIGH_FREQUENCY_REFERENCE_IASIG = $300B;
  AL_ENV_LISTENER_ENVIRONMENT_IASIG = $300C;
  AL_ENV_SOURCE_ENVIRONMENT_IASIG = $300D;

  ALC_INVALID = -1;
  ALC_FALSE = 0;
  ALC_TRUE = 1;
  ALC_NO_ERROR = ALC_FALSE;

  ALC_MAJOR_VERSION = $1000;
  ALC_MINOR_VERSION = $1001;
  ALC_ATTRIBUTES_SIZE = $1002;
  ALC_ALL_ATTRIBUTES = $1003;
  ALC_DEFAULT_DEVICE_SPECIFIER = $1004;
  ALC_DEVICE_SPECIFIER = $1005;
  ALC_EXTENSIONS = $1006;
  ALC_FREQUENCY = $1007;
  ALC_REFRESH = $1008;
  ALC_SYNC = $1009;

  ALC_INVALID_DEVICE = $A001;
  ALC_INVALID_CONTEXT = $A002;
  ALC_INVALID_ENUM = $A003;
  ALC_INVALID_VALUE = $A004;
  ALC_OUT_OF_MEMORY = $A005;

implementation

end.